# environment:
#   matrix:
#   - GENERATOR: MinGW Makefiles
#     BUILD_TYPE: Release
# 
# before_build:
#   # Workaround for CMake not wanting sh.exe on PATH for MinGW
#   - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
#   - set PATH=C:\MinGW\bin;%PATH%
#   - mkdir build
#   - cd build
#   - cmake -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -G "%GENERATOR%" ..
# 
# build_script: cmake --build . --config %BUILD_TYPE%
environment:
  matrix:
  - GENERATOR: MinGW Makefiles

configuration: Debug

before_build:
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "%GENERATOR%" ..

build_script: cmake --build . --config %CONFIGURATION%
