image:
  - Visual Studio 2015
environment:
  matrix:
  - GENERATOR: MinGW Makefiles
    platform: x64

configuration: Debug

# clone_script:
#   - git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
#   - cd %APPVEYOR_BUILD_FOLDER%
#   - git checkout -qf %APPVEYOR_REPO_COMMIT%
#   - git submodule update --init --recursive

before_build:
  - rm -rf build
  - rm -rf stage
  - git submodule init
  - git submodule update
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "%GENERATOR%" ../super

build_script: cmake --build . --config %CONFIGURATION%
